# monitoring/rules/rca_alerts.yml
groups:
- name: rca_system_alerts
  rules:
  
  # High error rate in RCA analyses
  - alert: HighRCAErrorRate
    expr: (rate(rca_analysis_total{status="error"}[5m]) / rate(rca_analysis_total[5m])) * 100 > 5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High RCA analysis error rate"
      description: "RCA analysis error rate is {{ $value }}% which is above 5%"

  # Slow RCA analysis performance
  - alert: SlowRCAAnalysis
    expr: histogram_quantile(0.95, rate(rca_analysis_duration_seconds_bucket[5m])) > 30
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "RCA analysis taking too long"
      description: "95th percentile RCA analysis time is {{ $value }}s"

  # Model accuracy degradation
  - alert: ModelAccuracyDegraded
    expr: model_accuracy < 0.8
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "ML model accuracy has degraded"
      description: "Model accuracy is {{ $value }} which is below 80%"

  # High memory usage
  - alert: HighMemoryUsage
    expr: (system_memory_usage_bytes / 1024 / 1024 / 1024) > 4
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High system memory usage"
      description: "System memory usage is {{ $value }}GB"

  # Vector DB issues
  - alert: VectorDBConnectionIssues
    expr: rate(vector_db_operations_total{status="error"}[5m]) > 0.1
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Vector database connection issues"
      description: "Vector DB error rate is {{ $value }} ops/sec"

  # No recent analyses (system might be down)
  - alert: NoRecentAnalyses
    expr: increase(rca_analysis_total[10m]) == 0
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: "No RCA analyses performed recently"
      description: "No RCA analyses have been performed in the last 10 minutes"

  # Low user satisfaction
  - alert: LowUserSatisfaction
    expr: rate(user_satisfaction_score_sum[1h]) / rate(user_satisfaction_score_count[1h]) < 3
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Low user satisfaction with RCA results"
      description: "Average user satisfaction is {{ $value }}/5"